pages: # the job must be named pages
  image: node:latest
  stage: deploy
  before_script:
    # - ./update_version.sh
    - echo $CI_COMMIT_TIMESTAMP $CI_COMMIT_SHORT_SHA > src/assets/version.txt
    - npm install -g workbox-cli
  script:
    - npm ci
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - main

s3-deploy:
  stage: .post
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
  - aws s3 sync ./public s3://weblite-production-shared-shared-bucket --delete --only-show-errors
  only:
  - master